name: PR Build
on:
  pull_request:

jobs:
  build:
    name: Validate Builds
    runs-on: self-hosted

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        path: gsm
    
    - name: Build Linux
      run: |
        go build -o gamemanager -v github.com/Game-Server-Management/gsm-main
        go test -v ./...
      env:
        GOOS: linux
        GOARCH: amd64

    