name: GSM Builder

on:
  push:
    branches: [ master ]

jobs:
  gamesbuilder:
    strategy:
      fail-fast: false
      matrix:
        go: [ '^1.16' ]
        goos: [ linux ]
        goarch: [ amd64, arm64 ]
        games: [ sampserver ]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go v${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
        SRC_PATH: github.com/Game-Server-Management/gsm-main
      run: go build -trimpath -o build/${{matrix.games}}_${GOOS}_${GOARCH} -v games/${{matrix.games}}/main.go

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v2
      if: ${{ github.ref == 'refs/heads/master' || github.event_name == 'commit' }}
      with:
        name: ${{matrix.games}}_${{ matrix.goos }}_${{ matrix.goarch }}
        path: build/${{matrix.games}}_${{ matrix.goos }}_${{ matrix.goarch }}

    - name: Commit Files
      run: |
        git config user.name "${{ github.actor }}"
        git add .
        git commit -m "upload: New Binaries for Applications"
        git push origin master
  gamemanager:
    strategy:
      fail-fast: false
      matrix:
        go: [ '^1.16' ]
        goos: [ linux ]
        goarch: [ amd64, arm64 ]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go v${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
        SRC_PATH: github.com/Game-Server-Management/gsm-main
      run: go build -trimpath -o build/gamemanager_${GOOS}_${GOARCH} -v main.go

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v2
      if: ${{ github.ref == 'refs/heads/master' || github.event_name == 'commit' }}
      with:
        name: gamemanager_${{ matrix.goos }}_${{ matrix.goarch }}
        path: build/gamemanager_${{ matrix.goos }}_${{ matrix.goarch }}

    - name: Commit Files
      run: |
        git config user.name "${{ github.actor }}"
        git add .
        git commit -m "upload: New Binaries for Applications"
        git push origin master
